### ISSUE TITLE
Add suport for uploading images

### ISSUE THREAD

**Issue by 0xae** [IgorAntun/node-chat#10]
Could you add suport for uploading images, if storage is a problem, you can write a script that deletes images every seconds or so.
:+1:

**Comment by daimajia** [comment]
+1

**Comment by DerpgonCz** [comment]
@0xae or just upload them to third party - imgur.com, vgy.me etc.

**Comment by 0xae** [comment]
My cat will love this (although i dont have one)

**Comment by IgorAntun** [comment]
Closing this as it would add a whole lot of work for something that might not be well worth it. We now have inline images thanks to #17, so, uploading the image to imgur or some other site and just pasting the link in the chat should be enough.
