### ISSUE TITLE
MongDB Support

### ISSUE THREAD

**Issue by igor9silva** [IgorAntun/node-chat#12]
What do you think of changing the dataset to Mongo?
I could work in a port.

**Comment by IgorAntun** [comment]
Feel free to fork it and implement MongoDB, but for now we're sticking with MySQL to handle databases :)

**Comment by igor9silva** [comment]
I've just read the code and it seems not to be storing the messages.
Am I right?

If so, do you plan to store the messages or you'll keep like that?

**Comment by IgorAntun** [comment]
Yes, messages are not being stored.
We are keeping like that for now. May change in the future.
