### ISSUE TITLE
Show IP to Administrators on connect & disconnect

### ISSUE THREAD

**Issue by Kickball** [IgorAntun/node-chat#14]
Show the IP to administrators upon user connection or disconnect.

Example:

Users:

   ```System    IgorAntun connected to the server.```

Administrators:

   ```System    IgorAntun (8.8.8.8) connected to the server.```

**Comment by Kickball** [comment]
Any updates on this issue?

**Comment by IgorAntun** [comment]
It can be done by tomorrow or the day after. Thanks for reminding.

**Comment by IgorAntun** [comment]
This will take some extra effort, since only admins should receive the user IP. I need to send a different object to a) Users and b) Admins.
