### ISSUE TITLE
Centralized Config File

### ISSUE THREAD

**Issue by Kickball** [IgorAntun/node-chat#15]
Move all of the configuration of the server to a single file (config.json)

I would suggest moving the following settings there:

* MessagesPerSecond
* IP
* Port
* LogFileLocation
* LogLevel
* SSLCertificateLocation
* SSLKeyLocation

**Comment by Kickball** [comment]
Any updates on this issue?

**Comment by IgorAntun** [comment]
Sorry, didn't really have time to dedicate on this project lately. I can do this by tomorrow or the day after, thanks for reminding me!
