### ISSUE TITLE
How do I scrape in as admin

### ISSUE THREAD

**Issue by AgariosCom** [IgorAntun/node-chat#16]
How and where do I add myself admin How to connect to the chat admin please help please I would be glad if you could put as much visual Thank you very much in advance

**Comment by IgorAntun** [comment]
Hey :) At the moment you can use /role (your-name) directly on your app console if you enabled the input, it'll automatically promote you to the maximum admin level.

**Comment by AgariosCom** [comment]
Connecting the chat console app can not write anything but active console code is not write

**Comment by IgorAntun** [comment]
Remember you must have the `config.readline` variable set to true (it can be found at https://github.com/IgorAntun/node-chat/blob/master/app.js#L18) to be able to use the console to promote yourself.

**Comment by AgariosCom** [comment]
Thank you very much thank you automatically get one number for all it is appreciated if connecting a great chat when you're alone, though this chat www.agarios.com integrates hits records are broken into nicknames such persons connected to the game
