### ISSUE TITLE
Command to list all users

### ISSUE THREAD

**Issue by zoo1** [IgorAntun/node-chat#18]
Is it possible to get a command that could list all users on the client? /users or something?

**Comment by IgorAntun** [comment]
Hey, thanks for the suggestion!
There is a button in the menu that lists all the users. Are you talking about a command that lists the users in the chat (as a message), or could it just open the popup with the user list (as the button does)?

**Comment by zoo1** [comment]
The same as the button does, but I was unaware of the button when opening this issue. If you think it functionality is repetitive feel free to close this issue.

**Comment by IgorAntun** [comment]
Ok, I can make the command trigger the popup as the button does :)

**Comment by zoo1** [comment]
Are you open to PRs on this repo? I was thinking about killing a couple issues.

**Comment by IgorAntun** [comment]
Sure! Any PR is welcome! :)

**Comment by IgorAntun** [comment]
Done in #19 - Thanks to @zoo1
