### ISSUE TITLE
Blop.wav not reproducing on Firefox

### ISSUE THREAD

**Issue by lisandro52** [IgorAntun/node-chat#23]
Hi! It's me again.
After I spent some more time with the chat, I noticed that the "blop" sound wouldn't play on Firefox.
After some digging, I found that Firefox can't reproduce WAV files encoded with more than 16 bits, so I re-encoded the ``blop.wav`` file to 16 bits, and it now works properly.

Another issue I found with the sound is that the ``chat.js`` file wasn't properly loaded by Firefox, because the ``speechToText`` variable is only defined on Chrome, so I added a definition check for that and everything is running nicely! Again, I'm about to add a pull request to this issue so you can check it and merge.
Cheers!

**Comment by IgorAntun** [comment]
That's true, I guess I need to do more testing huh? Thank you once again for your contributions, those are always welcome and appreciated!
