### ISSUE TITLE
The demo website is not working

### ISSUE THREAD

**Issue by hvu53** [IgorAntun/node-chat#25]

**Comment by IgorAntun** [comment]
Yeah, that's an issue with the SSL cert. renewal which I'm fixing. Thanks for reporting! :)

**Comment by IgorAntun** [comment]
At last, online again! New URL: https://vps.antun.me/node-chat/

**Comment by rohitkrishna094** [comment]
how can we deploy it so that the chat app works on internet not just on local machine, so that the url can be shared? can we deploy it to github pages? or do we need heroku or some other backend? I am new to nodejs. thanks.

**Comment by igorantun** [comment]
Hello @rohitkrishna094 , you will need a backend, such as Heroku, to keep the websocket server online. The frontend alone can be hosted with Github Pages, but won't work without the backend.
