### ISSUE TITLE
About admins

### ISSUE THREAD

**Issue by systemroot** [IgorAntun/node-chat#33]
i'm not too good with nodejs, 

maybe anyone here know how to save admin account's, or when i login with my ip/username server will give me admin role directly?!

Thanks!

**Comment by IgorAntun** [comment]
Hey!

To save accounts you would need to:
**a)** always allow admin permissions based on nickname (insecure)
or **b)** use something such as MongoDB and implement a signup/login system (auth).

Example of how to give permissions based on IP/Username:
```javascript
if(clients[id].ip === 'IP' || name ===  'NAME') {
  utils.sendToAll(clients, {
    message: name + ' logged in as an Administrator',
    user: 'System',
    type: 'role',
    extra: name,
    role: 3
  });
  utils.sendToOne(clients, users, {role: 3}, name, 'role');
}
```
This should go at the end of the `updateUser` function, starting at around line 184 of `index.js`
Make sure to change `IP` and `NAME` to your actual IP and username.

Cheers!

**Comment by systemroot** [comment]
@IgorAntun as i said i'm not to good with nodejs so i can't setup a auth with a database, 
so i know that do give admin permissions from username isn't good because everyone can login with my username, so for that i asked to set it from ip,

Thank you very much!

**Comment by IgorAntun** [comment]
You're welcome! Feel free to ping me if you have more questions :)
