### ISSUE TITLE
store chat?

### ISSUE THREAD

**Issue by DungBuiDeveloper** [igorantun/node-chat#38]
Project is AMAZING! do you plan to develop an application capable of storing messages?

**Comment by igorantun** [comment]
Hey there @DungBuiDeveloper ! Yes, I do. I plan on developing a new version of this project, using more modern technology, and a backend storage is definitely planned. There is a discussion about the new project on #36 :)

**Comment by DungBuiDeveloper** [comment]
yes thank for rep
