### ISSUE TITLE
Add different moderation ranks

### ISSUE THREAD

**Issue by Cazeh** [IgorAntun/node-chat#4]
Add moderation ranks like Administrator, Moderator, Trial-Mod, Special, Coder, Designer, etc...

**Comment by IgorAntun** [comment]
Already started working on it. I'll probably go with 3 ranks:
Helper (blue): Can delete messages and kick users.
Moderator (green): The above plus banning users.
Administrator (red): The above plus sending global alerts and giving/taking mod perms to/from other users.

**Comment by IgorAntun** [comment]
It's done on version 0.17.19.
